config/routes.rb
Rails.application.routes.draw do
  # need rout to landing page
  get "/", to: "landing_page#index", as: "landing_page"

  #users
  # root to: "users#index

  # show all
  get "/users", to: "users#index", as: "users"
  # create new prof
  get "/users/new", to: "users#new", as: "new_user"
  # create prof
  post "/users", to: "users#create"
  # show user details
  get "/users/:user_id", to: "users#show", as: "user"
  # edit
  get "/users/:user_id/edit", to: "users#edit", as: "edit_user"
  # update
  patch "/users/:user_id", to: "users#update", as: "update_user"
  put "/users/:user_id", to: "users#update"
  # delete
  delete "/users/:user_id", to: "users#destroy", as: "delete_user"
    
  #events
  get "/users/:user_id/events", to: "events#index", as: "events"
  get "/users/:user_id/events/new", to: "events#new", as: "new_event"
  post "/users/:user_id/events", to: "events#create"
  #show all vote details (render scores)
  post "/users/:user_id/events/:event_id", to: "events#vote", as: "vote"
  # post "/users/:user_id/events/:event_id", to: "events#sun_vote", as: "sun_vote"

  get "/users/:user_id/events/:event_id", to: "events#show", as: "event"
  # create event done by vote logic, just need tp edit/update
  # edit event. 
  get "/users/:user_id/events/:event_id/edit", to: "events#edit", as: "edit_event"
  patch "/users/:user_id/events/:event_id", to: "events#update", as: "update_event"
  put "/users/:user_id/events/:event_id", to: "events#update"
  delete "/users/:user_id/events", to: "events#destroy", as: "delete_event"

  #sessions
  get "/signin", to: "sessions#new", as: "sign_in"
  #create session,mmn
  post "/sessions", to: "sessions#create"
  #logout session
  delete "/sessions", to: "sessions#destroy", as: "logout_user"

  #messages
  #show all
  get "/users/:user_id/messages", to: "messages#index", as: "messages"
  #create new msg
  get "/users/:user_id/messages/new", to: "messages#new", as: "new_message"
  # post new msg
  post "/users/:user_id/messages", to: "messages#create", as: "post_message"
  #show full msg details... might not need this
  get "/users/:user_id/messages/:message_id", to: "messages#show", as: "message"
  #edit msg ... might not need this
  get "/users/:user_id/messages/:message_id/edit", to: "messages#edit", as: "edit_message"
  #update
  patch "/users/:user_id/messages/:messages_id", to: "messages#update", as: "update_message"
  put "/users/:user_id/messages/:messages_id", to: "users#update"
  #delete
  delete "/users/:user_id/messages", to: "messages#destroy", as: "delete_message"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  validates :content, :user_id, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in?, only: :index
  def index
    @messages = Message.all
    render :index
  end

  def show
    @message = Message.find(params[:message_id])
    render :show
  end

  def new
    @message = Message.new
    render :new
  end

  def create
    p "hey from create"
    @message = current_user.messages.new(message_params)
    if @message.save
      # login(@user)
      redirect_to messages_path
      flash[:notice] = "message posted!"
    else 
      flash[:notice] = "somethings wrong"
      redirect_to "/events"
    end
  end

  def edit
    @message = Message.find(params[:message_id])
     render :edit
    # if authorize?
    #   # if @right_person
    #   render :edit
    # else 
    #   redirect_to "/events"
    # end
  end

  def update
    @message = Message.find(params[:message_id])
    # update the user
    @message.update_attributes(message_params)
    redirect_to "/events"
  end

  def destroy
    Message.destroy(params[:message_id])
  end

  private
  def message_params
    #must this be full validation params??
     params.require(:message).permit(:content, :user_id)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'message_form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="msgs-background">
<h1>All Messages</h1>

<% if flash[:notice] %>
  <div class="notice"> <%= flash[:notice] %>  </div>
<%end%>
<%= button_to 'New message', new_message_path, method: :get, class: "btn btn-success btn-lg" %>

<div id="messages">
    <% @messages.each do |message| %>
      <div class="row">
        <div class="msg-content col-md-3 col-centered ">
          Message: <%= message.content %> 
          <br>
          From: <%= message.user.name %> 
        </div>
        <!-- broke ass link -->
      </div>
    <% end %>
</div>
</div>

<!-- link to msg details? -->

<br>

<!-- need link to SHOW message details, method_path -->

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'message_form' %>

<%= link_to 'Back', messages_path %>

<br>
<br>
<br>
<br>
<br>

app/views/messages/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>