config/routes.rb
Rails.application.routes.draw do
  # need rout to landing page
  get "/", to: "landing_page#index", as: "landing_page"

  #users
  # root to: "users#index

  # show all
  get "/users", to: "users#index", as: "users"
  # create new prof
  get "/users/new", to: "users#new", as: "new_user"
  # create prof
  post "/users", to: "users#create"
  # show user details
  get "/users/:user_id", to: "users#show", as: "user"
  # edit
  get "/users/:user_id/edit", to: "users#edit", as: "edit_user"
  # update
  patch "/users/:user_id", to: "users#update", as: "update_user"
  put "/users/:user_id", to: "users#update"
  # delete
  delete "/users/:user_id", to: "users#destroy", as: "delete_user"
    
  #events
  get "/users/:user_id/events", to: "events#index", as: "events"
  get "/users/:user_id/events/new", to: "events#new", as: "new_event"
  post "/users/:user_id/events", to: "events#create"
  #show all vote details (render scores)
  post "/users/:user_id/events/:event_id", to: "events#vote", as: "vote"
  # post "/users/:user_id/events/:event_id", to: "events#sun_vote", as: "sun_vote"

  get "/users/:user_id/events/:event_id", to: "events#show", as: "event"
  # create event done by vote logic, just need tp edit/update
  # edit event. 
  get "/users/:user_id/events/:event_id/edit", to: "events#edit", as: "edit_event"
  patch "/users/:user_id/events/:event_id", to: "events#update", as: "update_event"
  put "/users/:user_id/events/:event_id", to: "events#update"
  delete "/users/:user_id/events", to: "events#destroy", as: "delete_event"

  #sessions
  get "/signin", to: "sessions#new", as: "sign_in"
  #create session,mmn
  post "/sessions", to: "sessions#create"
  #logout session
  delete "/sessions", to: "sessions#destroy", as: "logout_user"

  #messages
  #show all
  get "/users/:user_id/messages", to: "messages#index", as: "messages"
  #create new msg
  get "/users/:user_id/messages/new", to: "messages#new", as: "new_message"
  # post new msg
  post "/users/:user_id/messages", to: "messages#create", as: "post_message"
  #show full msg details... might not need this
  get "/users/:user_id/messages/:message_id", to: "messages#show", as: "message"
  #edit msg ... might not need this
  get "/users/:user_id/messages/:message_id/edit", to: "messages#edit", as: "edit_message"
  #update
  patch "/users/:user_id/messages/:messages_id", to: "messages#update", as: "update_message"
  put "/users/:user_id/messages/:messages_id", to: "users#update"
  #delete
  delete "/users/:user_id/messages", to: "messages#destroy", as: "delete_message"

end

app/models/user.rb
class User < ActiveRecord::Base
  #relationships
  include EventsHelper

  has_many :messages
  has_many :events
  has_secure_password

  # validations
  validates :name, :email, :password, presence: true


  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

  def self.sanity_check
    # event_check
    p "hey from User model!"
    # ApplicationMailer.final_date_email(self)deliver!
  end

  # def send_final_date_email
  #   ApplicationMailer.final_date_email(self)deliver!
  # end
  # make hella validations
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: :index
  #show all users page (from nav)
  # def landing_page
  #   render "test"
  # end

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.create(user_params)
    login(@user)

    # test mail
    ApplicationMailer.final_date_email(@user).deliver!

    # redirect_to "/users/#{@user.id}"
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:user_id])
    render :show
  end

  def edit
    @user = User.find(params[:user_id])
    if authorize?
      # if @right_person
        render :edit
      else 
        redirect_to "/"
      end
    # render :edit
  end

  def update
    p "hey from update"
    @user = User.find(params[:user_id])
    # update the user
    @user.update_attributes(user_params)
    # redirect_to "/users/#{@user.id}"
    redirect_to user_path
  end

  def destroy
    log_out
    User.destroy(params[:user_id])
    redirect_to "/"
    flash[:notice] = "You have successfully logged out."
    # redirect_to landing_page
  end

  private
  def user_params
    params.require(:user).permit(:name, :origin, :pic, :neighborhood, :bio, :email, :password)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
Edit Your Profile

<%= form_for @user, url: update_user_path, method: :patch  do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.text_field :origin, placeholder: "Origin" %>
  </div>
  <div>
    <%= f.text_field :pic, placeholder: "Pic" %>
  </div>
  <div>
    <%= f.text_field :neighborhood, placeholder: "Neighborhood" %>
  </div>
  <div>
    <%= f.text_field :bio, placeholder: "Bio" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.text_field :password, placeholder: "password" %>
  </div>
  <%= f.submit "Update", class: "btn btn-secondary btn-lg"%>
<% end %> 

app/views/users/index.html.erb
<h1>Hoops Crew Playas</h1>

<div>
<h3> There are currently <%= @users.length %> players signed up </h3>
</div>
<br>

<div>
  <% @users.each do |user| %>
    <div class="player-content col-md-3 col-centered">
      Name:   <%= user.name %>
      origin: <%= user.origin %>
      'hood:  <%= user.neighborhood %>
      <%= link_to "See Full Payer Profile", user_path(user), method: :get, class: "btn btn-secondary btn-sm" %>
    </div>
    <br>
  <%end%>
</div>

app/views/users/new.html.erb
Sign Up For Hoops Crew!

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.text_field :origin, placeholder: "Origin" %>
  </div>
  <div>
    <%= f.text_field :pic, placeholder: "Pic" %>
  </div>
    <div>
    <%= f.text_field :neighborhood, placeholder: "neighborhood" %>
  </div>
    <div>
    <%= f.text_field :bio, placeholder: "Bio" %>
  </div>
    <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-success" %>
<% end %> 

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/users/show.html.erb
<h1> Player Profile </h1>
<div class="player-profile col-md-3 col-centered" >
  <h1>  <%= @user.name %> </h1> 
  <div> Prof Pic: <%= @user.pic %> </div>
  <div> Origin: <%= @user.origin %> </div>
  <div> Hood: <%= @user.neighborhood %> </div>
  <div> Bio: <%= @user.bio %> </div>
  <div> Email: <%= @user.email %> </div>
</div>

<br>

<div>
    <% if authorize? %>
      <%= button_to "see all playas", users_path, method: :get, class: "prof-btns btn btn-secondary btn-sm "%>
      <%= button_to "Edit user", edit_user_path(@user), method: :get, class: "prof-btns btn btn-secondary btn-sm" %>
      <%= button_to "Delete user", @user, method: :delete, class: "prof-btns btn btn-danger btn-sm" %>
      <%= button_to "logout", logout_user_path(@user), method: :delete, class: "prof-btns btn btn-secondary btn-sm" %>
    <%else%>
      <%= link_to "see all playas", "/users" %>
    <% end %>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>