config/routes.rb
Rails.application.routes.draw do
  # need rout to landing page
  get "/", to: "landing_page#index", as: "landing_page"

  #users
  # root to: "users#index

  # show all
  get "/users", to: "users#index", as: "users"
  # create new prof
  get "/users/new", to: "users#new", as: "new_user"
  # create prof
  post "/users", to: "users#create"
  # show user details
  get "/users/:user_id", to: "users#show", as: "user"
  # edit
  get "/users/:user_id/edit", to: "users#edit", as: "edit_user"
  # update
  patch "/users/:user_id", to: "users#update", as: "update_user"
  put "/users/:user_id", to: "users#update"
  # delete
  delete "/users/:user_id", to: "users#destroy", as: "delete_user"
    
  #events
  get "/users/:user_id/events", to: "events#index", as: "events"
  get "/users/:user_id/events/new", to: "events#new", as: "new_event"
  post "/users/:user_id/events", to: "events#create"
  #show all vote details (render scores)
  post "/users/:user_id/events/:event_id", to: "events#vote", as: "vote"
  # post "/users/:user_id/events/:event_id", to: "events#sun_vote", as: "sun_vote"

  get "/users/:user_id/events/:event_id", to: "events#show", as: "event"
  # create event done by vote logic, just need tp edit/update
  # edit event. 
  get "/users/:user_id/events/:event_id/edit", to: "events#edit", as: "edit_event"
  patch "/users/:user_id/events/:event_id", to: "events#update", as: "update_event"
  put "/users/:user_id/events/:event_id", to: "events#update"
  delete "/users/:user_id/events", to: "events#destroy", as: "delete_event"

  #sessions
  get "/signin", to: "sessions#new", as: "sign_in"
  #create session,mmn
  post "/sessions", to: "sessions#create"
  #logout session
  delete "/sessions", to: "sessions#destroy", as: "logout_user"

  #messages
  #show all
  get "/users/:user_id/messages", to: "messages#index", as: "messages"
  #create new msg
  get "/users/:user_id/messages/new", to: "messages#new", as: "new_message"
  # post new msg
  post "/users/:user_id/messages", to: "messages#create", as: "post_message"
  #show full msg details... might not need this
  get "/users/:user_id/messages/:message_id", to: "messages#show", as: "message"
  #edit msg ... might not need this
  get "/users/:user_id/messages/:message_id/edit", to: "messages#edit", as: "edit_message"
  #update
  patch "/users/:user_id/messages/:messages_id", to: "messages#update", as: "update_message"
  put "/users/:user_id/messages/:messages_id", to: "users#update"
  #delete
  delete "/users/:user_id/messages", to: "messages#destroy", as: "delete_message"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer>
  <p> All rights reserved Hoops Crew International 2016 </p>
</footer>

app/views/application/_message_form.html.erb
<%= form_for @message, method: :post do |f| %>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
     <!-- follow for pic etc -->
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success"%>
  </div>
  
<% end %>

app/views/application/_navbar.html.erb
<header> 
  <nav class="navbar navbar-light bg-faded">
    <ul class="nav navbar-nav">
      <li class="nav-item"> 
        <%= link_to "Home", landing_page_path, method: "get" %> 
      </li>
      <% if current_user %>
      <li class="nav-item" > 
      <!-- needs to get event.id -->
        <%= link_to "Vote", event_path(current_user, 1), method: "get" %> 
      </li>
      <li class="nav-item"> 
        <%= link_to "Profile", user_path(current_user), method: "get" %> 
        </li>
      <li class="nav-item"> 
        <%= link_to "Roster", users_path, method: "get" %> 
      </li>
      <li class="nav-item"> 
        <%= link_to "Message Board", messages_path(current_user), method: "get" %> 
      </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/application/_weather.html.erb
<br>
<h1 id="event-page-title"> Vote on What day we Ball </h1>
<h3> Weekend Forcast </h3>

<div id="main-event">
  <h4>For weekend of</h4>
    <%= @event.weekend_date %>

  <div class="row">
    <div class="col-lg-6">
      <div id="saturday-forcast"> 
        <h3> Saturday Forcast:</h3>
        <i id="sat-weather-icon-id"></i>
        <div id="sat-desciption">sat desciption</div>
        <div id="sat-temp"> temp </div>
      </div>
    </div>

    <div class="col-lg-6">
      <div id="sunday-forcast">
        <h3> Sunday Forcast:</h3>
        <i id="sun-weather-icon-id"> </i>
        <div id="sun-desciption">sun desciption</div>
        <div id="sun-temp"> temp </div>
      </div>
    </div>

  </div>

</div>



<div id="scoreboard">
  <div class="row">
    <div class="col-lg-6">
      <h3> Saturday Votes:</h3>
      <div class="vote-count">
        <%= @event.sat_votes%>
      </div>
      <% if current_user.voted == nil %>
        <%= button_to "sat vote", {:url => update_event_path, :controller => "events", :action => "vote", :event_id => @event.id, :vote_day => "sat", :method => :post}, class: "btn btn-success" %>
      <% end %>
  </div>
  <div class="col-lg-6">
      <h3> Sunday Votes:</h3>
        <div class="vote-count">
          <%= @event.sun_votes %>
        </div>
        <!-- copy current user logic from above -->
      <% if current_user.voted == nil %>
        <%= button_to "sun vote", {:url => update_event_path, :controller => "events", :action => "vote", :event_id => @event.id, :vote_day => "sun", :method => :post}, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


  
<% if flash[:notice] %>
  <div class="notice"> <%= flash[:notice] %>  </div>
<%end%>